templateRepository:
  gitProvider: s_gitHub
  path: "{{.jfrog-pipelines.sourceRepository}}"
  branch: "{{gitBranch}}"
  templateFolder: templates/

publishTemplate:
  namespace: jfrogPipelines
  name: templateDefinition
  version: 0.0.1
  pipelineName: Publish_Template_10113
  artifactoryIntegration: s_artifactory
  jfrogAccessTokenIntegration: jfrogAccessToken_10390
  templateRepositoryResourceName: Publish_Template_10390_01
  templateUploadStatusResourceName: Publish_Template_10390_1
