stableBaseImages:
  ubuntu18: 'company.jfrog.io/infosec_docker_local/ubuntu18:1.0.0'
  ubuntu20: 'company.jfrog.io/infosec_docker_local/ubuntu20:2.1.0'

teams:
  - name: app_team_1
    sourceCode:
      repositoryPath: 'kunal-mazumdar/pipelines-local-test-repo'
      branch: 'riotGames'
      gitIntegration: test_git
    destinationRepo: 'company.jfrog.io/app_team_1_docker_local'
    targets:
      - baseImageName: ubuntu18
        targetImageName: 'u18_go'
        targetImageVersion: '2.0.0'
        language:
          name: go
          version: 1.19
          tools:
            - sonar

      - baseImageName: ubuntu20
        targetImageName: 'u20_java'
        targetImageVersion: '2.1.0'
        language:
          name: java
          version: 18
          tools:
            - sonar

  - name: app_team_2
    sourceCode:
      repositoryPath: 'kunal-mazumdar/pipelines-local-test-repo'
      branch: 'riotGames'
      gitIntegration: test_git
    destinationRepo: 'company.jfrog.io/app_team_2_docker_local'
    targets:
      - baseImageName: ubuntu20
        targetImageName: 'u20_go'
        targetImageVersion: '1.1.0'
        language:
          name: go
          version: 1.19
          tools:
            - sonar
